//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show information about EDI.
        /// </summary>
        public static string CMD_APP_About_Description {
            get {
                return ResourceManager.GetString("CMD_APP_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close document.
        /// </summary>
        public static string CMD_APP_CloseDoc_Description {
            get {
                return ResourceManager.GetString("CMD_APP_CloseDoc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string CMD_App_Exit_Describtion {
            get {
                return ResourceManager.GetString("CMD_App_Exit_Describtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file ....
        /// </summary>
        public static string CMD_APP_Open_Description {
            get {
                return ResourceManager.GetString("CMD_APP_Open_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL ....
        /// </summary>
        public static string CMD_APP_OpenURL_Description {
            get {
                return ResourceManager.GetString("CMD_APP_OpenURL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All ....
        /// </summary>
        public static string CMD_APP_SaveAll_Description {
            get {
                return ResourceManager.GetString("CMD_APP_SaveAll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Start Page.
        /// </summary>
        public static string CMD_APP_ShowStartPage_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ShowStartPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View application theme.
        /// </summary>
        public static string CMD_APP_ViewTheme_Description {
            get {
                return ResourceManager.GetString("CMD_APP_ViewTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MRU Entry.
        /// </summary>
        public static string CMD_MRU_AddEntry_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_AddEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin or unpin an MRU entry.
        /// </summary>
        public static string CMD_MRU_Pin_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_Pin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove MRU Entry.
        /// </summary>
        public static string CMD_MRU_RemoveEntry_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_RemoveEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch off syntax highlighting for current file.
        /// </summary>
        public static string CMD_TXT_DisableHighlighting_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_DisableHighlighting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindNext_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindNext_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next occurrance of specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindNextText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindNextText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find previous occurrance of specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindPreviousText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindPreviousText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace a specific text in a document.
        /// </summary>
        public static string CMD_TXT_FindReplaceText_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_FindReplaceText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to a specific line in a document.
        /// </summary>
        public static string CMD_TXT_GotoLine_Description {
            get {
                return ResourceManager.GetString("CMD_TXT_GotoLine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to clipboard.
        /// </summary>
        public static string STR_AppCommand_CopyFileURLToClipboard {
            get {
                return ResourceManager.GetString("STR_AppCommand_CopyFileURLToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the path of this document into the Windows Clipboard.
        /// </summary>
        public static string STR_AppCommand_CopyFileURLToClipboard_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_CopyFileURLToClipboard_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing folder....
        /// </summary>
        public static string STR_AppCommand_OpenContainingFolder {
            get {
                return ResourceManager.GetString("STR_AppCommand_OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the folder that contains this document in Windows Explorer.
        /// </summary>
        public static string STR_AppCommand_OpenContainingFolder_TT {
            get {
                return ResourceManager.GetString("STR_AppCommand_OpenContainingFolder_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string STR_Category_Error {
            get {
                return ResourceManager.GetString("STR_Category_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string STR_Category_Information {
            get {
                return ResourceManager.GetString("STR_Category_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string STR_Category_InternalError {
            get {
                return ResourceManager.GetString("STR_Category_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Internal Error.
        /// </summary>
        public static string STR_Category_Unknown_Internal_Error {
            get {
                return ResourceManager.GetString("STR_Category_Unknown_Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string STR_Category_UnknownError {
            get {
                return ResourceManager.GetString("STR_Category_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string STR_Category_Warning {
            get {
                return ResourceManager.GetString("STR_Category_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string STR_CmdName_Close {
            get {
                return ResourceManager.GetString("STR_CmdName_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string STR_CmdName_Copy {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item.
        /// </summary>
        public static string STR_CmdName_Copy_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Copy_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string STR_CmdName_Cut {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected item.
        /// </summary>
        public static string STR_CmdName_Cut_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Cut_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string STR_CmdName_Delete {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item.
        /// </summary>
        public static string STR_CmdName_Delete_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Delete_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string STR_CmdName_Edit {
            get {
                return ResourceManager.GetString("STR_CmdName_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string STR_CmdName_Exit {
            get {
                return ResourceManager.GetString("STR_CmdName_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string STR_CmdName_File {
            get {
                return ResourceManager.GetString("STR_CmdName_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string STR_CmdName_Find {
            get {
                return ResourceManager.GetString("STR_CmdName_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to line....
        /// </summary>
        public static string STR_CmdName_GotoLine {
            get {
                return ResourceManager.GetString("STR_CmdName_GotoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string STR_CmdName_Help {
            get {
                return ResourceManager.GetString("STR_CmdName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string STR_CmdName_Help_About {
            get {
                return ResourceManager.GetString("STR_CmdName_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Message Tool Window.
        /// </summary>
        public static string STR_CmdName_Log4Net_Message_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Log4Net_Message_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Tool Window.
        /// </summary>
        public static string STR_CmdName_Log4Net_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Log4Net_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string STR_CmdName_New {
            get {
                return ResourceManager.GetString("STR_CmdName_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document.
        /// </summary>
        public static string STR_CmdName_New_Text {
            get {
                return ResourceManager.GetString("STR_CmdName_New_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a text file.
        /// </summary>
        public static string STR_CmdName_New_Text_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_New_Text_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UML Document.
        /// </summary>
        public static string STR_CmdName_New_UML {
            get {
                return ResourceManager.GetString("STR_CmdName_New_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a uml file.
        /// </summary>
        public static string STR_CmdName_New_UML_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_New_UML_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string STR_CmdName_Open {
            get {
                return ResourceManager.GetString("STR_CmdName_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Document.
        /// </summary>
        public static string STR_CmdName_Open_Log4Net {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Log4Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Log4Net file.
        /// </summary>
        public static string STR_CmdName_Open_Log4Net_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Log4Net_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document.
        /// </summary>
        public static string STR_CmdName_Open_Text {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a text file.
        /// </summary>
        public static string STR_CmdName_Open_Text_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_Text_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UML Document.
        /// </summary>
        public static string STR_CmdName_Open_UML {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_UML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an UML file.
        /// </summary>
        public static string STR_CmdName_Open_UML_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Open_UML_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string STR_CmdName_Paste {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste item from Windows clipboard.
        /// </summary>
        public static string STR_CmdName_Paste_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Paste_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Tool Window.
        /// </summary>
        public static string STR_CmdName_Properties_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_Properties_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Documents.
        /// </summary>
        public static string STR_CmdName_RecentFiles {
            get {
                return ResourceManager.GetString("STR_CmdName_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files Tool Window.
        /// </summary>
        public static string STR_CmdName_RecentFiles_TW {
            get {
                return ResourceManager.GetString("STR_CmdName_RecentFiles_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string STR_CmdName_Redo {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undo.
        /// </summary>
        public static string STR_CmdName_Redo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Redo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string STR_CmdName_Replace {
            get {
                return ResourceManager.GetString("STR_CmdName_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string STR_CmdName_Save {
            get {
                return ResourceManager.GetString("STR_CmdName_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current file.
        /// </summary>
        public static string STR_CmdName_Save_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Save_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        public static string STR_CmdName_SaveAs {
            get {
                return ResourceManager.GetString("STR_CmdName_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as certain type and in certain location.
        /// </summary>
        public static string STR_CmdName_SaveAs_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_SaveAs_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string STR_CmdName_SelectAll {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all items.
        /// </summary>
        public static string STR_CmdName_SelectAll_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_SelectAll_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Themes.
        /// </summary>
        public static string STR_CmdName_Themes {
            get {
                return ResourceManager.GetString("STR_CmdName_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string STR_CmdName_Tools {
            get {
                return ResourceManager.GetString("STR_CmdName_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string STR_CmdName_Undo {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last edit.
        /// </summary>
        public static string STR_CmdName_Undo_TT {
            get {
                return ResourceManager.GetString("STR_CmdName_Undo_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string STR_CmdName_View {
            get {
                return ResourceManager.GetString("STR_CmdName_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string STR_CmdName_View_Start_Page {
            get {
                return ResourceManager.GetString("STR_CmdName_View_Start_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert or overtype text mode (switch on/of with insert key).
        /// </summary>
        public static string STR_Insert_Overtype_Mode_TT {
            get {
                return ResourceManager.GetString("STR_Insert_Overtype_Mode_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the link below to check if this is a known problem.
        ///
        ///Please report this problem if it is not known, yet.
        ///
        ///The problem report should contain the error message below (you can use the copy button)
        ///and a statement about the function/workflow you were using. Attach screenshots or sample files if applicable..
        /// </summary>
        public static string STR_MSG_IssueTrackerText {
            get {
                return ResourceManager.GetString("STR_MSG_IssueTrackerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        public static string STR_MSG_IssueTrackerTitle {
            get {
                return ResourceManager.GetString("STR_MSG_IssueTrackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string STR_Msg_UnknownError {
            get {
                return ResourceManager.GetString("STR_Msg_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        public static string STR_MSG_UnknownError_Caption {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while dispatching unhandled exception.
        /// </summary>
        public static string STR_MSG_UnknownError_InErrorDispatcher {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_InErrorDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in shut-down process..
        /// </summary>
        public static string STR_MSG_UnknownError_InShutDownProcess {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError_InShutDownProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string STR_StatusBar_Ready {
            get {
                return ResourceManager.GetString("STR_StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endcoding of the text in the current document.
        /// </summary>
        public static string STR_StatusBar_Textencoding_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_Textencoding_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string STR_StatusBar_X_Coord_Label {
            get {
                return ResourceManager.GetString("STR_StatusBar_X_Coord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column of the cursor in the current document.
        /// </summary>
        public static string STR_StatusBar_X_Coord_Label_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_X_Coord_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string STR_StatusBar_Y_Coord_Label {
            get {
                return ResourceManager.GetString("STR_StatusBar_Y_Coord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row of the cursor in the current document.
        /// </summary>
        public static string STR_StatusBar_Y_Coord_Label_TT {
            get {
                return ResourceManager.GetString("STR_StatusBar_Y_Coord_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text highlighting pattern.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_HighlightingDefinition_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_HighlightingDefinition_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show End of Line.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowEndOfLine {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show end of line.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowEndOfLine_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowEndOfLine_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Line Numbers.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowLineNumbers {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show line numbers.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowLineNumbers_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowLineNumbers_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Spaces.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowSpaces {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show space characters.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowSpaces_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowSpaces_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tabs.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowTabs {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabulator characters.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_ShowTabs_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_ShowTabs_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_WordWrap {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap text around document view.
        /// </summary>
        public static string STR_ToggleEditorOptionCmd_WordWrap_TT {
            get {
                return ResourceManager.GetString("STR_ToggleEditorOptionCmd_WordWrap_TT", resourceCulture);
            }
        }
    }
}
